"""empty message

Revision ID: 7cbc7d3aaa59
Revises: 
Create Date: 2019-07-10 13:20:55.515649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cbc7d3aaa59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BankDetails',
    sa.Column('ifsc', sa.VARCHAR(length=30), nullable=False),
    sa.Column('bank_id', sa.BigInteger(), nullable=True),
    sa.Column('branch', sa.TEXT(), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('city', sa.TEXT(), nullable=True),
    sa.Column('district', sa.TEXT(), nullable=True),
    sa.Column('state', sa.TEXT(), nullable=True),
    sa.Column('bank_name', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('ifsc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('BankDetails')
    # ### end Alembic commands ###
